<?php

    $helper = $this->helper( '\Magento\Backend\Helper\Data' );

    $html = <<<HTML
<script type="text/javascript">
    require(['EcomailBackOffice'], function(EcomailBackOffice) {
        EcomailBackOffice.init({1});
    });
</script>
HTML;

    $html = strtr(
            $html,
            array(
                    '{1}' => json_encode(
                            array(
                                    'formFieldAPIKey' => 'ecomail_options_properties_api_key',
                                    'formFieldList' => 'ecomail_options_properties_list_id',
                                    'formFieldRowSelector' => 'tr',
                                    'ajaxUrl' => $helper->getUrl( 'adminhtml/ecomail/ajax' ),
                                    'templates' => array(
                                            'connect' => <<<HTML
<tr>
  <td class="label">
  </td>
  <td class="value">
    <input type="submit" value="Připojit" id="{BUTTON_CONNECT}" class="btn">
  </td>
  <td class="scope-label"></td>
  <td class=""></td>
</tr>
HTML

                                    )
                            )
                    )
            )
    );

    echo $html;