<?php
/** @var \Ecomail\Ecomail\Helper\Data $helper */
$helper = $this->helper(\Ecomail\Ecomail\Helper\Data::class);
?>
<?php if ($helper->isTrackingEnabled()): ?>
    <script type="text/javascript">
        ;(function(p,l,o,w,i,n,g){if(!p[i]){p.GlobalSnowplowNamespace=p.GlobalSnowplowNamespace||[];
            p.GlobalSnowplowNamespace.push(i);p[i]=function(){(p[i].q=p[i].q||[]).push(arguments)
            };p[i].q=p[i].q||[];n=l.createElement(o);g=l.getElementsByTagName(o)[0];n.async=1;
            n.src=w;g.parentNode.insertBefore(n,g)}}(window,document,"script","//d70shl7vidtft.cloudfront.net/ecmtr-2.4.2.js","ecotrack"));
        window.ecotrack('newTracker', 'cf', 'd2dpiwfhf3tz0r.cloudfront.net', { /* Initialise a tracker */
            appId: '<?= $helper->getAppId() ?>'
        });
        window.ecotrack('setUserIdFromLocation', 'ecmid');
        window.ecotrack('trackPageView');
    </script>

    <script>
        require([
            'Magento_Customer/js/customer-data'
        ], function(customerData) {
            customerData.get('ecomail').subscribe(function(items) {
                if(items && items.email) {
                    window.ecotrack('setUserId', items.email);
                    window.ecotrack('trackPageView');

                    customerData.reload('ecomail', true);
                }
            });
        });
    </script>
<?php endif; ?>
