<?php /** @var \Ecomail\Ecomail\Block\Tracking $block */ ?>
<?php if ($block->isTrackingEnabled() || $block->isFormEnabled()): ?>
    <?php
    $config = [
        'Ecomail_Ecomail/js/tracking' => [
            'waitForCookieConsent' => $block->shouldWaitForCookieConsent(),
            'trackingEnabled' => $block->isTrackingEnabled(),
            'appId' => $block->getAppId(),
            'trackProductView' => $block->shouldTrackProductView(),
            'productCode' => $block->getCurrentProductCode(),
            'formEnabled' => $block->isFormEnabled(),
            'formId' => $block->getFormId(),
            'formAccount' => $block->getFormAccount(),
        ],
    ];
    ?>
    <div data-mage-init='<?= $block->escapeHtmlAttr(json_encode($config, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT)) ?>'></div>
<?php endif; ?>
